---
# Application
web_app_name: devops-app
web_app_docker_image: your_dockerhub_username/devops-info-service
web_app_docker_tag: latest
web_app_port: 8000
web_app_internal_port: 8000
web_app_env: {}

# Docker Compose
web_app_docker_compose_version: "3.8"
web_app_compose_project_dir: "/opt/{{ web_app_name }}"

web_app_dockerhub_username: ""
web_app_dockerhub_password: ""

# Wipe Logic Control
web_app_wipe: false
