apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-info
  labels:
    app: devops-info
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-info
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: devops-info
    spec:
      containers:
        - name: devops-info
          image: woolfer0097kek/devops-info-python:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 2
          env:
            - name: PORT
              value: "5000"
