{{- if and .Values.hooks.enabled .Values.hooks.preInstall.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "devops-info.fullname" . }}-pre-install"
  labels:
    {{- include "devops-info.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "{{ .Values.hooks.preInstall.weight }}"
    "helm.sh/hook-delete-policy": "{{ .Values.hooks.deletePolicy }}"
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 30
  template:
    metadata:
      name: "{{ include "devops-info.fullname" . }}-pre-install"
      labels:
        {{- include "devops-info.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: pre-install
          image: {{ .Values.hooks.image }}
          command:
            - /bin/sh
            - -c
            - {{ .Values.hooks.preInstall.command | quote }}
{{- end }}
