replicaCount: 5

image:
  tag: "1.0.0"

service:
  type: LoadBalancer
  nodePort: null

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

probes:
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 5
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 3
